#!/bin/bash

fullname_gith="danholdaway"

email_gith="danholdaway@users.noreply.github.com"

case "$url" in
  *@github.com:*          ) name="${fullname_gith}"; email="${email_gith}";;
  *//github.com/*         ) name="${fullname_gith}"; email="${email_gith}";;
  github:*                ) name="${fullname_gith}"; email="${email_gith}";;
esac

unset fullname_gith
unset email_gith
